version: 2.1

orbs:
  ruby: circleci/ruby@2.0.1

jobs:
  test:
    docker:
      - image: cimg/ruby:3.2-node
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: art_gallery_test
          POSTGRES_PASSWORD: ""
    environment:
      RAILS_ENV: test
    steps:
      - checkout
      - run:
          name: Install dockerize
          command: curl -L https://github.com/jwilder/dockerize/releases/download/v0.6.1/dockerize-linux-amd64-v0.6.1.tar.gz | tar -xz -C /usr/local/bin
      - run:
          name: Install dependencies
          command: bundle install --path vendor/bundle
      - run:
          name: Wait for PostgreSQL
          command: dockerize -wait tcp://localhost:5432 -timeout 90s
      - run:
          name: Database setup
          command: bundle exec rake db:create db:migrate
      - run:
          name: Run tests
          command: bundle exec rspec

workflows:
  build-and-test:
    jobs:
      - test
