version: 2.1

orbs:
  ruby: circleci/ruby@2.0.1

jobs:
  test:
    docker:
      - image: cimg/ruby:3.2-node
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: art_gallery_test
          POSTGRES_PASSWORD: ""
    environment:
      RAILS_ENV: test
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: bundle config set path 'vendor/bundle' && bundle install
      - run:
          name: Wait for database
          command: dockerize -wait tcp://localhost:5432 -timeout 60s
      - run:
          name: Setup database
          command: bundle exec rake db:create db:migrate
      - run:
          name: Run tests
          command: bundle exec rspec

workflows:
  build-and-test:
    jobs:
      - test

